services:
  postgres:
    image: postgres:17
    container_name: nexihub_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nexihub
    ports:
      - '5432:5432'